print("Hello World")
print(66)
print(True)
print("Hi, I am Aumit Hasan and I am ",23,"Years old")
print("This is a",10,"on",10,"performance")
print("That,s all for this program and I will see you in the next one. Thank you")